### ISSUE TITLE
Parsing fails if trailing new line is omitted.

### ISSUE THREAD

**Issue by Angular-Angel** [PixelGuys/TrivialJson#1]
When I try and load a JSON file, if I omit the trailing newline, I get the following error:

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because the return value of "java.io.BufferedReader.readLine()" is null
	at pixelguys.json.JsonParser.parseObjectFromStream(JsonParser.java:24)

The fix on my end is simple enough, but it might be worth patching so that Trivial JSON does not require a trailing newline? Up to you I guess.

**Comment by IntegratedQuantum** [comment]
It should work now.
I decided to also make some changes to the function itself, it's now called `parseObjectFromBufferedReader` and takes a second argument `endOfMessage` which can be used for network streams to mark the end of the json input.
Since you don't need it, you can just set it to null.
